version: '2'
services:
    btcars-app:
        image: btcars
        external_links:
            - btcars-mysql:mysql
            - btcars-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/btcars?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    btcars-mysql:
        extends:
            file: mysql.yml
            service: btcars-mysql
    btcars-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: btcars-elasticsearch
